import type { Locale, LocalizedText, StatKey } from "../game/types";
import { STAT_NAMES } from "../game/content";

const text = (zh: string, en: string): LocalizedText => ({ zh, en });

export const UI_COPY = {
  gameTitle: text("行旅之契", "Covenant of the Road"),
  seriesTitle: text("山河有契", "Mountains & Rivers"),
  documentTitle: text("行旅之契 · 山河有契", "Covenant of the Road · Mountains & Rivers"),
  documentDescription: text(
    "一段由选择写成的山河旅程。",
    "A journey through mountains and rivers, written by your choices.",
  ),
  introKicker: text("一纸旧契 · 五段山河", "One old covenant · Five regions"),
  introTitle: text("你带来的，是一封信，还是一条路？", "Did you carry a letter—or a road?"),
  introBody: text(
    "从芦渡到天门关，每一次取舍都会被山河记住。这段短程行旅会随行自动存档。",
    "From Reed Ferry to Sky Gate, the land remembers every choice. This short journey saves as you travel.",
  ),
  begin: text("启程", "Begin journey"),
  newJourney: text("换一张旅签", "New route"),
  replay: text("循原路再走一次", "Replay this route"),
  language: text("English", "中文"),
  languageLabel: text("Switch to English", "切换到中文"),
  skipToStory: text("跳到行旅正文", "Skip to journey"),
  routeSeed: text("旅签", "Route seed"),
  progress: text("行程", "Journey"),
  journal: text("行旅笺", "Travel journal"),
  journalEmpty: text("尚未落笔。", "No marks yet."),
  chronicle: text("山河志", "Journey chronicle"),
  endingsDiscovered: text("结局", "Endings"),
  encountersShort: text("遭遇", "Encounters"),
  journeysRecorded: text("所录行路", "Routes recorded"),
  recentJourneys: text("近日行路", "Recent journeys"),
  replayRecordedJourney: text("重走此行", "Replay this journey"),
  confirmReplayRecordedJourney: text("确认舍下当前行路并重走", "Confirm leaving this journey to replay"),
  confirmLeaveJourney: text("确认舍下未竟之行", "Confirm leaving unfinished journey"),
  replayReplacesJourney: text("再次按下同一条行路，将舍下当前未竟旅程。", "Press the same route again to leave the current unfinished journey."),
  undiscoveredEnding: text("未闻之途", "Undiscovered path"),
  encountersDiscovered: text("已访山河", "Encounters discovered"),
  undiscoveredEncounter: text("未识", "Unknown"),
  preferences: text("阅览设置", "Reading settings"),
  textScale: text("字号", "Text size"),
  textNormal: text("标准", "Default"),
  textLarge: text("放大", "Large"),
  motion: text("动态", "Motion"),
  motionSystem: text("跟随系统", "System"),
  motionReduced: text("减少动态", "Reduced"),
  contrast: text("对比度", "Contrast"),
  contrastSystem: text("跟随系统", "System"),
  contrastHigh: text("高对比", "High"),
  ambient: text("山水环境音", "Landscape ambience"),
  ambientPlay: text("开启环境音", "Play ambience"),
  ambientStarting: text("正在开启环境音……", "Starting ambience…"),
  ambientStop: text("关闭环境音", "Stop ambience"),
  ambientMute: text("静音", "Mute"),
  ambientUnmute: text("取消静音", "Unmute"),
  ambientVolume: text("音量", "Volume"),
  ambientUnavailable: text("此浏览器无法播放环境音。", "Ambient audio is unavailable in this browser."),
  ambientFailed: text("无法开始播放；旅程仍可静默进行。", "Playback could not start; the journey remains fully playable in silence."),
  ambientPausedWhenHidden: text(
    "切换页面时已暂停环境音；需要时请重新开启。",
    "Ambience paused when the page was hidden; start it again when wanted.",
  ),
  storageDurability: text("本地数据保护", "Local data protection"),
  storageChecking: text("正在检查浏览器是否保护本地数据……", "Checking whether the browser protects local data…"),
  storageBestEffort: text(
    "进度已存于本机，但存储空间紧张时浏览器仍可能自动清除。",
    "Progress is saved locally, but the browser may still remove it automatically under storage pressure.",
  ),
  storageProtect: text("请求保护本地数据", "Ask browser to protect local data"),
  storageRequesting: text("正在请求浏览器保护……", "Requesting browser protection…"),
  storageProtectionGranted: text("已获浏览器保护", "Browser protection granted"),
  storageProtected: text(
    "已防止浏览器自动清除；你仍可在站点设置或游戏内自行删除。",
    "Protected from automatic browser eviction; you can still clear it in site settings or in the game.",
  ),
  storageDenied: text(
    "浏览器未授予自动清除保护；请导出备份以长期保管。",
    "The browser did not grant eviction protection; export a backup for long-term safekeeping.",
  ),
  storageProtectionUnavailable: text(
    "此浏览器不报告自动清除保护状态；请导出备份以长期保管。",
    "This browser does not report eviction protection; export a backup for long-term safekeeping.",
  ),
  storageProtectionFailed: text(
    "无法检查或请求自动清除保护；请导出备份以长期保管。",
    "Eviction protection could not be checked or requested; export a backup for long-term safekeeping.",
  ),
  backup: text("本地备份", "Local backup"),
  backupDescription: text("导出旅程、山河志与阅览设置；恢复前会先验证文件。", "Export the journey, chronicle, and reading settings; files are validated before restore."),
  backupExport: text("导出进度", "Export progress"),
  backupExported: text("备份已交给浏览器下载。", "Backup sent to the browser for download."),
  backupExportFailed: text(
    "无法开始下载；请复制下方备份数据并保存为 JSON 文件。",
    "The download could not start; copy the backup data below and save it as a JSON file.",
  ),
  backupFallbackLabel: text("可手动复制的备份数据", "Manually copyable backup data"),
  backupChoose: text("选择备份", "Choose backup"),
  backupRestore: text("恢复此备份", "Restore this backup"),
  backupClear: text("清除本地数据", "Clear local data"),
  backupClearConfirm: text("确认清除全部数据", "Confirm clearing all data"),
  backupClearPrompt: text("再次按下确认；旅程、山河志与设置将永久删除。", "Press again to confirm; the journey, chronicle, and settings will be permanently deleted."),
  backupClearing: text("正在清除并重新载入……", "Clearing and reloading…"),
  backupClearFailed: text("无法清除本地数据；现有记录保持不变。", "Local data could not be cleared; existing records are unchanged."),
  backupClearRollbackFailed: text("无法清除本地数据，且未能完整恢复原记录。请重新载入后检查浏览器站点数据。", "Local data could not be cleared and the prior records could not be fully restored. Reload, then inspect this site's browser data."),
  backupReady: text("备份有效，可以恢复。", "Backup validated and ready to restore."),
  backupReadyCompacted: text(
    "旧版备份有效；已保留最近 128 次行路及全部已发现结局与遭遇，可以恢复。",
    "Legacy backup validated; the newest 128 journeys and every discovered ending and encounter are ready to restore.",
  ),
  backupReading: text("正在验证备份……", "Validating backup…"),
  backupInvalid: text("这不是有效的《山河有契》备份。当前进度未改变。", "This is not a valid Mountains & Rivers backup. Current progress is unchanged."),
  backupTooLarge: text("备份文件过大，未读取。当前进度未改变。", "The backup file is too large and was not read. Current progress is unchanged."),
  backupUnavailable: text("此浏览器无法使用本地备份。", "Local backup is unavailable in this browser."),
  backupRestoring: text("正在恢复并重新载入……", "Restoring and reloading…"),
  backupRestoreFailed: text("无法写入备份；当前进度保持不变。", "The backup could not be written; current progress is unchanged."),
  backupRestoreRollbackFailed: text("无法写入备份，且未能完整恢复原记录。请重新载入后检查浏览器站点数据。", "The backup could not be written and the prior records could not be fully restored. Reload, then inspect this site's browser data."),
  backupPersistenceUnavailable: text("浏览器无法写入本地存储，无法恢复备份。仍可导出本次旅程。", "Writable browser storage is unavailable, so backups cannot be restored. This session can still be exported."),
  persistenceUnavailable: text("浏览器无法写入本地存储。本次旅程仍可继续，但刷新后不会保留。", "Writable browser storage is unavailable. This journey remains playable, but a refresh will reset it."),
  updateReady: text("新版本已离线备妥。", "A newer version is ready offline."),
  updateResetsSession: text("持久存储不可用；重新载入会重置本次旅程。", "Persistent storage is unavailable; reloading will reset this session."),
  applyUpdate: text("重新载入更新", "Reload to update"),
  applyingUpdate: text("正在更新……", "Updating…"),
  externalChangeKicker: text("本地进度有变", "Local progress changed"),
  externalChangeTitle: text("另一页已更新这段行旅", "Another tab updated this journey"),
  externalChangeDescription: text(
    "继续操作会覆盖较新的记录。请重新载入，再从另一页的进度继续。",
    "Continuing here could overwrite newer progress. Reload before continuing from the other tab's state.",
  ),
  externalChangeReload: text("载入最新进度", "Load latest progress"),
  externalUpdateKicker: text("离线版本有变", "Offline version changed"),
  externalUpdateTitle: text("另一页已启用新版本", "Another tab activated an update"),
  externalUpdateDescription: text(
    "这页已停止操作，以免混用两个版本。请重新载入新版本后继续。",
    "This tab has stopped to avoid mixing two versions. Reload the new version before continuing.",
  ),
  externalUpdateReload: text("重新载入新版本", "Reload new version"),
  externalChangeReloadPending: text("正在重新载入……", "Reloading…"),
  shareJourney: text("分享此行", "Share this journey"),
  summaryLabel: text("可复制的行旅摘要", "Selectable journey summary"),
  copyJourney: text("抄录行旅", "Copy journey"),
  downloadJourney: text("下载行旅文本", "Download journey text"),
  nativeShareJourney: text("用系统分享", "Share with device"),
  copied: text("已抄录到剪贴板。", "Copied to clipboard."),
  downloaded: text("行旅文本已交给浏览器下载。", "Journey text sent to the browser for download."),
  downloadFailed: text(
    "无法开始下载；请从上方摘要中手动复制行旅。",
    "The download could not start; manually copy the journey summary above.",
  ),
  copyFailed: text("无法使用剪贴板，请选择上方文字手动复制。", "Clipboard unavailable; select the text above to copy manually."),
  shared: text("已交给系统分享。", "Sent to the device share sheet."),
  shareFailed: text("无法打开系统分享；仍可抄录或手动复制上方文字。", "The device share sheet could not open; copy or select the text above instead."),
  choicePrompt: text("你如何回应？", "How do you answer?"),
  reflectionKicker: text("余响", "Aftermath"),
  onward: text("继续前行", "Continue onward"),
  reflectionHint: text("按 Enter 继续", "Press Enter to continue"),
  endingKicker: text("此行已毕", "Journey complete"),
  keyboardHint: text("按 1 或 2 选择 · L 切换语言", "Press 1 or 2 to choose · L changes language"),
  endingHint: text("按 R 沿原路重来", "Press R to replay this route"),
  requirement: text("尚需", "Requires"),
  stats: STAT_NAMES,
} as const;

export const localize = (value: LocalizedText, locale: Locale): string => value[locale];

export const statLabel = (stat: StatKey, locale: Locale): string =>
  localize(UI_COPY.stats[stat], locale);
