extends SceneTree

const ExplorationStateScript := preload("res://src/domain/exploration_state.gd")
const SaveGameScript := preload("res://src/domain/save_game.gd")
const SettingsStoreScript := preload("res://src/domain/settings_store.gd")
const TEST_SAVE_PATH := "user://automated-e2e-save.json"
const TEST_SETTINGS_PATH := "user://automated-e2e-settings.json"

var assertions := 0
var failures: Array[String] = []


func _initialize() -> void:
	_run.call_deferred()


func _run() -> void:
	SaveGameScript.remove(TEST_SAVE_PATH)
	SettingsStoreScript.remove(TEST_SETTINGS_PATH)
	var scene: PackedScene = load("res://src/ui/main.tscn")
	var game := scene.instantiate()
	game.configure_save_path(TEST_SAVE_PATH)
	game.configure_settings_path(TEST_SETTINGS_PATH)
	root.add_child(game)
	await _settle()

	_expect(game.get_node("%TitleOverlay").visible, "E2E 从标题界面开始")
	game.get_node("%NewGameButton").pressed.emit()
	await _settle()
	_expect(game.get_node("%LocationLabel").text == "照禾渡口", "E2E 新游戏进入照禾渡口")
	await _trigger_semantic_action(game, "interact")
	await _settle()
	_expect(game.dialogue.active and game.get_node("%DialogueOverlay").visible, "E2E 交互开启逐句风险简报")
	_expect(game.get_node("%DialoguePortrait").visual_contract()["portrait_id"] == "yanqing", "E2E 开场台词显示砚青纸绘头像")
	game.show_full_dialogue_line()
	game.advance_dialogue()
	_expect(game.get_node("%DialoguePortrait").visual_contract()["portrait_id"] == "protagonist", "E2E 第二句切换为主角纸绘头像")
	game.show_full_dialogue_line()
	game.advance_dialogue()
	var interrupted_line: int = game.dialogue.line_index
	var interrupted_text: String = game.get_node("%DialogueLabel").text
	game.queue_free()
	await _settle()
	game = scene.instantiate()
	game.configure_save_path(TEST_SAVE_PATH)
	game.configure_settings_path(TEST_SETTINGS_PATH)
	root.add_child(game)
	await _settle()
	_expect(game.continue_game(), "E2E 可从新场景恢复对话中途存档")
	_expect(game.dialogue.active and game.dialogue.line_index == interrupted_line, "E2E 中断恢复保持对话行号")
	_expect(game.get_node("%DialogueLabel").text == interrupted_text, "E2E 中断恢复保持当前台词")
	game.skip_dialogue_to_response()
	await _settle()
	_expect(game.get_node("%DialoguePortrait").visual_contract()["portrait_id"] == "protagonist", "E2E 回应阶段明确由主角作出选择")
	await _press_dialogue_choice(game, "先看退路，再进山。")
	_expect(game.journey.talked_to_companion, "E2E 选择谨慎回应完成风险简报")
	_expect(game.get_node("%ObjectiveLabel").text.contains("月芽田"), "E2E 简报后任务切换到采药")
	_expect(game.exploration.restore({"map_id": "zhaohe_ferry", "player_x": 0.41, "player_y": 0.66}), "E2E 到达渡口守堤人")
	game._render([])
	await _trigger_semantic_action(game, "interact")
	_expect(game.dialogue.dialogue_id == "ferryman_briefing", "E2E 开启守堤支线对话")
	_expect(game.get_node("%DialoguePortrait").visual_contract()["portrait_id"] == "liangshu", "E2E 守堤台词显示梁叔纸绘头像")
	game.skip_dialogue_to_response()
	await _settle()
	await _press_dialogue_choice(game, "一起扶正水尺。")
	_expect(game.journey.ferryman_response == "repair", "E2E 主路线保存扶尺选择")
	_expect(game.get_node("%MapCanvas").ferryman_visual_contract()["gauge_upright"], "E2E 扶尺后地图残留直立水尺")
	_expect(game.exploration.restore({"map_id": "zhaohe_ferry", "player_x": 0.43, "player_y": 0.42}), "E2E 到达渡口旧水痕")
	game._render([])
	await _trigger_semantic_action(game, "interact")
	_expect(game.journey.discoveries == ["ferry_watermark"], "E2E 语义交互记录渡口见闻")
	_expect(game.get_node("%EventLabel").text.contains("转移药苗"), "E2E 呈现渡口环境历史")
	_expect(game.exploration.restore({"map_id": "zhaohe_ferry", "player_x": 0.47, "player_y": 0.51}), "E2E 调查后回到同行起点")
	game._render([])

	game.move_player(Vector2.DOWN, 0.40)
	game.move_player(Vector2.RIGHT, 0.74)
	await _settle()
	await _trigger_semantic_action(game, "interact")
	await _settle()
	_expect(game.journey.gathered_moonleaf, "E2E 通过语义交互采集月芽草")
	_expect(game.journey.moonleaf_method == "whole_plant", "E2E 语义交互保留向后兼容的旧规取药")

	game.move_player(Vector2.LEFT, 0.82)
	game.move_player(Vector2.UP, 1.56)
	game.move_player(Vector2.RIGHT, 1.46)
	game.move_player(Vector2.DOWN, 0.06)
	await _settle()
	await _press_action(game, "进入藏泉山道")
	_expect(game.journey.phase_id() == "mountain_path", "E2E 从山门进入可探索山道")
	_expect(game.exploration.map_id == "cangquan_path", "E2E 山道使用独立地图标识")
	_expect(game.exploration.restore({"map_id": "cangquan_path", "player_x": 0.40, "player_y": 0.30}), "E2E 到达石缝泉纹")
	game._render([])
	await _trigger_semantic_action(game, "interact")
	_expect(game.journey.discoveries == ["ferry_watermark", "spring_seam"], "E2E 山道见闻追加到同一存档列表")
	_expect(SaveGameScript.read(TEST_SAVE_PATH)["data"]["exploration"]["map_id"] == "cangquan_path", "E2E 山道地图与坐标自动保存")
	game.queue_free()
	await _settle()
	game = scene.instantiate()
	game.configure_save_path(TEST_SAVE_PATH)
	game.configure_settings_path(TEST_SETTINGS_PATH)
	root.add_child(game)
	await _settle()
	_expect(game.continue_game(), "E2E 可从新场景恢复山道中途存档")
	_expect(game.journey.phase_id() == "mountain_path" and game.exploration.map_id == "cangquan_path", "E2E 中途恢复保持剧情与地图一致")
	_expect(game.journey.discoveries == ["ferry_watermark", "spring_seam"], "E2E 中途恢复保持已读环境见闻")
	_expect(game.journey.ferryman_response == "repair", "E2E 中途恢复保持守堤选择")
	game.get_node("%SceneTransition").finish()
	await _settle()
	game.open_journal()
	await _settle()
	var resumed_journal: Dictionary = game.journal_contract()
	_expect(resumed_journal["visible"] and resumed_journal["discovered_count"] == 2, "E2E 读档后的札记恢复两处见闻")
	_expect(resumed_journal["entries_text"].contains("分向旧圃的泉纹"), "E2E 札记显示已恢复的山道条目")
	_expect(resumed_journal["unlocked_titles"].has("扶正的照禾水尺"), "E2E 札记恢复守堤结果")
	_expect(not resumed_journal["entries_text"].contains("换过两次的提绳"), "E2E 札记不剧透仍未发现的药篓标题")
	game.close_journal()
	var resumed_follow: Dictionary = game.get_node("%MapCanvas").companion_follow_contract()
	_expect(resumed_follow["context_id"] == "mountain_path" and resumed_follow["point_count"] == 2, "E2E 读档在当前地图重建同行轨迹")
	_expect(game.exploration.player_position.distance_to(resumed_follow["normalized_position"]) < 0.05, "E2E 读档把砚青放在主角安全近旁")
	_expect(game.exploration.restore({"map_id": "cangquan_path", "player_x": 0.68, "player_y": 0.60}), "E2E 到达弃置药篓")
	game._render([])
	await _trigger_semantic_action(game, "interact")
	_expect(game.journey.discoveries == ["ferry_watermark", "spring_seam", "abandoned_basket"], "E2E 药篓生活痕迹进入持久见闻")
	_expect(game.get_node("%EventLabel").text.contains("提绳"), "E2E 药篓调查呈现原创空间线索")
	_expect(game.exploration.restore({"map_id": "cangquan_path", "player_x": 0.10, "player_y": 0.68}), "E2E 到达山道退路")
	game._render([])
	await _trigger_semantic_action(game, "interact")
	_expect(game.journey.phase_id() == "riverbank" and game.exploration.map_id == "zhaohe_ferry", "E2E 可从山道主动返回渡口")
	_expect(game.exploration.restore({"map_id": "zhaohe_ferry", "player_x": 0.75, "player_y": 0.66}), "E2E 带药篓到达渡口药圃守")
	game._render([])
	await _trigger_semantic_action(game, "interact")
	_expect(game.dialogue.active and game.dialogue.dialogue_id == "herbkeeper_basket", "E2E 开启蕙婶药篓支线")
	_expect(game.get_node("%DialoguePortrait").visual_contract()["portrait_id"] == "huishen", "E2E 药篓台词显示蕙婶纸绘头像")
	game.show_full_dialogue_line()
	game.advance_dialogue()
	var basket_line: int = game.dialogue.line_index
	var basket_text: String = game.get_node("%DialogueLabel").text
	game.queue_free()
	await _settle()
	game = scene.instantiate()
	game.configure_save_path(TEST_SAVE_PATH)
	game.configure_settings_path(TEST_SETTINGS_PATH)
	root.add_child(game)
	await _settle()
	_expect(game.continue_game(), "E2E 可从新场景恢复药篓对话")
	_expect(game.dialogue.dialogue_id == "herbkeeper_basket" and game.dialogue.line_index == basket_line, "E2E 药篓对话恢复保持稳定标识与行号")
	_expect(game.get_node("%DialogueLabel").text == basket_text, "E2E 药篓对话恢复保持当前台词")
	game.skip_dialogue_to_response()
	await _settle()
	await _press_dialogue_choice(game, "把药篓带回圃里。")
	_expect(game.journey.basket_response == "return", "E2E 主路线保存药篓归圃选择")
	_expect(game.get_node("%MapCanvas").basket_visual_contract()["returned_to_ferry"], "E2E 归圃后渡口留下公用药篓")
	game.open_journal()
	await _settle()
	_expect(game.journal_contract()["unlocked_titles"].has("回到药圃的公用篓"), "E2E 药篓结果进入内容驱动札记")
	game.close_journal()
	_expect(game.exploration.restore({"map_id": "zhaohe_ferry", "player_x": 0.88, "player_y": 0.18}), "E2E 返回后再次到达山门")
	game._render([])
	await _trigger_semantic_action(game, "interact")
	_expect(game.journey.phase_id() == "mountain_path", "E2E 返回后可以再次进入山道")
	_expect(game.exploration.restore({"map_id": "cangquan_path", "player_x": 0.43, "player_y": 0.57}), "E2E 到达旧石标")
	game._render([])
	await _trigger_semantic_action(game, "interact")
	_expect(game.get_node("%EventLabel").text.contains("箭记"), "E2E 调查旧石标")
	_expect(game.exploration.restore({"map_id": "cangquan_path", "player_x": 0.73, "player_y": 0.34}), "E2E 到达敌人预警区")
	game._render([])
	await _trigger_semantic_action(game, "interact")
	_expect(game.journey.phase_id() == "battle", "E2E 接近敌人才进入战斗")
	var unknown_intent_text: String = game.get_node("%ObjectiveLabel").text
	_expect(unknown_intent_text.contains("当前敌势") and unknown_intent_text.contains("试探冲撞") and unknown_intent_text.contains("3 伤害"), "E2E 未调查时仍明示当前敌势与伤害")
	_expect(not unknown_intent_text.contains("后一势") and not unknown_intent_text.contains("破绽窗口"), "E2E 未调查时不剧透后续行止与应对")
	await _press_action(game, "撤到旧石标")
	_expect(game.journey.phase_id() == "mountain_path", "E2E 可沿退路撤到山道")
	for spoor_case in [
		{"position": Vector2(0.65, 0.22), "intel_id": "rock_armor_young", "event_text": "两短一深"},
		{"position": Vector2(0.36, 0.43), "intel_id": "spring_moss_shell", "event_text": "孢尘"},
		{"position": Vector2(0.91, 0.34), "intel_id": "unbalanced_stone_puppet", "event_text": "拖痕"},
	]:
		_expect(game.exploration.restore({"map_id": "cangquan_path", "player_x": spoor_case["position"].x, "player_y": spoor_case["position"].y}), "E2E 到达三痕辨势位置")
		game._render([])
		await _trigger_semantic_action(game, "interact")
		_expect(game.journey.enemy_intel.has(spoor_case["intel_id"]), "E2E 调查后记录稳定灵物标识")
		_expect(game.get_node("%EventLabel").text.contains(spoor_case["event_text"]), "E2E 三处痕迹各自呈现原创空间线索")
	var spoor_visual: Dictionary = game.get_node("%MapCanvas").enemy_intel_visual_contract()
	_expect(spoor_visual["read_count"] == 3 and spoor_visual["studied"] == game.journey.enemy_intel, "E2E 三处已读痕迹保留地图残痕")
	game.open_journal()
	await _settle()
	game.select_journal_page(1)
	var intel_journal: Dictionary = game.journal_contract()
	_expect(intel_journal["page_title"] == "灵物志" and intel_journal["intel_count"] == 3, "E2E 灵物志为可选第二页并回显三项敌情")
	_expect(intel_journal["enemy_titles"].has("岩甲幼兽 · 两短一深") and intel_journal["entries_text"].contains("只在吸潮时"), "E2E 灵物志显示内容驱动的痕迹、行止与应对")
	game.close_journal()
	_expect(game.exploration.restore({"map_id": "cangquan_path", "player_x": 0.56, "player_y": 0.48}), "E2E 撤退后接近另一种敌人")
	game._render([])
	await _press_action(game, "触碰泉苔寄壳")
	_expect(game.journey.enemy_id == "spring_moss_shell", "E2E 非默认遭遇选择泉苔配置")
	_expect(game.get_node("%ObjectiveLabel").text.contains("吸潮蓄壳"), "E2E 战斗 UI 预告泉苔意图")
	_expect(game.get_node("%ObjectiveLabel").text.contains("后一势") and game.get_node("%ObjectiveLabel").text.contains("引气术"), "E2E 已读泉苔敌情显示后一势与当前破绽窗口")
	var saved_intent: String = game.journey.current_enemy_intent()["name"]
	game.queue_free()
	await _settle()
	game = scene.instantiate()
	game.configure_save_path(TEST_SAVE_PATH)
	game.configure_settings_path(TEST_SETTINGS_PATH)
	root.add_child(game)
	await _settle()
	_expect(game.continue_game(), "E2E 可从新场景恢复非默认敌人战斗")
	_expect(game.journey.enemy_id == "spring_moss_shell", "E2E 战斗恢复保持敌人标识")
	_expect(game.journey.current_enemy_intent()["name"] == saved_intent, "E2E 战斗恢复保持下一意图")
	await _press_action(game, "布置引泉石灯")
	_expect(game.journey.lamp_turns == 1, "E2E 战术石灯进入持续状态")
	await _press_action(game, "请砚青援护")
	await _press_action(game, "镇岩符")
	await _press_action(game, "引气术")
	_expect(game.journey.enemy_id == "rock_armor_warden", "E2E 普通遭遇后进入共享首领战")
	_expect(game.get_node("%ObjectiveLabel").text.contains("压阵肩撞"), "E2E 首领意图在行动前明示")
	_expect(game.get_node("%ObjectiveLabel").text.contains("后一势") and game.get_node("%ObjectiveLabel").text.contains("破绽窗口　无"), "E2E 岩甲痕迹也识别同类首领且不误报肩撞窗口")
	await _press_action(game, "守势调息")
	_expect(game.journey.armor_break_turns == 0, "E2E 守势在压阵肩撞时只做普通防御")
	_expect(game.get_node("%ObjectiveLabel").text.contains("崩石重击") and game.get_node("%ObjectiveLabel").text.contains("破绽窗口　守势调息"), "E2E 首领重击回合显示正确守势窗口")
	await _press_action(game, "守势调息")
	_expect(game.journey.armor_break_turns == 2, "E2E 守势只在首领重击回合施加破甲")
	await _press_action(game, "引气术")
	await _press_action(game, "请砚青援护")
	_expect(game.journey.focus_turns == 2, "E2E 同伴援护施加凝息")
	var boss_intent: String = game.journey.current_enemy_intent()["name"]
	game.queue_free()
	await _settle()
	game = scene.instantiate()
	game.configure_save_path(TEST_SAVE_PATH)
	game.configure_settings_path(TEST_SETTINGS_PATH)
	root.add_child(game)
	await _settle()
	_expect(game.continue_game(), "E2E 可恢复带状态的首领战")
	_expect(game.journey.armor_break_turns == 1 and game.journey.focus_turns == 2, "E2E 恢复保留破甲与凝息层数")
	_expect(game.journey.current_enemy_intent()["name"] == boss_intent, "E2E 首领恢复保持下一意图")
	await _press_action(game, "引气术")
	await _press_action(game, "引气术")
	_expect(game.journey.phase_id() == "spring", "E2E 击败首领后打开泉室")
	await _press_action(game, "静心引息")
	_expect(game.journey.phase_id() == "complete", "E2E 完成第一次引息")
	_expect(game.get_node("%DescriptionLabel").text.contains("本节结算"), "E2E 显示章节结算")
	_expect(game.get_node("%DescriptionLabel").text.contains("见闻 3/3"), "E2E 章节结算回显实际探索完成度")
	_expect(game.get_node("%DescriptionLabel").text.contains("敌情 3/3"), "E2E 章节结算回显三痕辨势完成度")
	_expect(game.get_node("%DescriptionLabel").text.contains("水尺扶正"), "E2E 章节结算回显扶尺选择")
	_expect(game.get_node("%DescriptionLabel").text.contains("药篓归圃"), "E2E 章节结算回显药篓归圃选择")
	_expect(SaveGameScript.read(TEST_SAVE_PATH)["data"]["journey"]["phase"] == "complete", "E2E 完成态已落盘")
	await _press_action(game, "回顾此行")
	_expect(game.dialogue.active and game.dialogue.dialogue_id == "chapter_epilogue", "E2E 完成态进入章节余波对话")
	_expect(game.get_node("%DialogueLabel").text.contains("沿途3处生活痕迹"), "E2E 余波回显实际见闻数量")
	_expect(game._resolved_dialogue_text("{intel_reflection}").contains("三种灵物"), "E2E 余波回显已辨明的三种灵物")
	_expect(game._resolved_dialogue_text("{ferryman_reflection}").contains("重新立稳"), "E2E 余波回显扶尺结果")
	_expect(game._resolved_dialogue_text("{basket_reflection}").contains("挂回圃门"), "E2E 余波回显药篓归圃结果")
	game.show_full_dialogue_line()
	game.advance_dialogue()
	var epilogue_line: int = game.dialogue.line_index
	var epilogue_text: String = game.get_node("%DialogueLabel").text
	game.queue_free()
	await _settle()
	game = scene.instantiate()
	game.configure_save_path(TEST_SAVE_PATH)
	game.configure_settings_path(TEST_SETTINGS_PATH)
	root.add_child(game)
	await _settle()
	_expect(game.continue_game(), "E2E 可从新场景恢复章节余波对话")
	_expect(game.journey.phase_id() == "complete" and game.dialogue.dialogue_id == "chapter_epilogue", "E2E 余波恢复保持完成态与对话标识")
	_expect(game.dialogue.line_index == epilogue_line and game.get_node("%DialogueLabel").text == epilogue_text, "E2E 余波恢复保持当前行与动态文本")
	game.get_node("%SceneTransition").finish()
	game.skip_dialogue_to_response()
	await _settle()
	await _press_dialogue_choice(game, "先把所见写进札记。")
	_expect(game.get_node("%EventLabel").text.contains("逐条写进札记"), "E2E 余波回应产生内容驱动回声")

	await _press_action(game, "完成本节并返回标题")
	_expect(game.get_node("%TitleOverlay").visible, "E2E 从结算返回标题")
	var completed_save_text := FileAccess.get_file_as_string(TEST_SAVE_PATH)
	game.get_node("%NewGameButton").pressed.emit()
	await _settle()
	_expect(game.new_game_confirmation_contract()["visible"], "E2E 有进度时重新开始先进入确认态")
	_expect(game.journey.phase_id() == "complete", "E2E 覆盖确认不提前替换完成态旅程")
	_expect(FileAccess.get_file_as_string(TEST_SAVE_PATH) == completed_save_text, "E2E 覆盖确认不提前改写存档")
	game.get_node("%ContinueButton").pressed.emit()
	await _settle()
	_expect(not game.new_game_confirmation_contract()["visible"], "E2E 取消覆盖回到普通标题态")
	_expect(FileAccess.get_file_as_string(TEST_SAVE_PATH) == completed_save_text, "E2E 取消覆盖保留完整存档")
	game.queue_free()
	await _settle()

	var resumed := scene.instantiate()
	resumed.configure_save_path(TEST_SAVE_PATH)
	resumed.configure_settings_path(TEST_SETTINGS_PATH)
	root.add_child(resumed)
	await _settle()
	_expect(not resumed.get_node("%ContinueButton").disabled, "E2E 新实例发现完成存档")
	resumed.get_node("%ContinueButton").pressed.emit()
	await _settle()
	_expect(resumed.journey.phase_id() == "complete", "E2E 继续游戏恢复完成态")
	await _press_action(resumed, "重游序章（重置进度）")
	_expect(resumed.journey.phase_id() == "riverbank", "E2E 重游回到序章起点")
	_expect(resumed.exploration.player_position == ExplorationStateScript.START_POSITION, "E2E 重游重置地图坐标")
	_expect(resumed.journey.enemy_intel.is_empty(), "E2E 重游只在明确重置时清空灵物志")
	resumed._on_action("talk_to_companion")
	resumed.skip_dialogue_to_response()
	await _press_dialogue_choice(resumed, "我信你的判断，一起走。")
	_expect(resumed.journey.briefing_response == "trusting", "E2E 重游可选择不同同行态度")
	_expect(resumed.exploration.restore({"map_id": "zhaohe_ferry", "player_x": 0.41, "player_y": 0.66}), "E2E 重游到达渡口守堤人")
	resumed._render([])
	await _trigger_semantic_action(resumed, "interact")
	resumed.skip_dialogue_to_response()
	await _settle()
	await _press_dialogue_choice(resumed, "先记下涨水时辰。")
	_expect(resumed.journey.ferryman_response == "record", "E2E 重游可选择记时分支")
	var recorded_visual: Dictionary = resumed.get_node("%MapCanvas").ferryman_visual_contract()
	_expect(recorded_visual["record_tag"] and not recorded_visual["gauge_upright"], "E2E 记时分支留下纸签而不扶正水尺")
	resumed._on_action("gather_moonleaf_cutting")
	_expect(resumed.journey.moonleaf_method == "cutting", "E2E 重游可选择剪叶留根")
	_expect(resumed.get_node("%MapCanvas").moonleaf_visual_contract()["regrowing"], "E2E 剪叶后地图显示留根新芽")
	resumed._on_action("enter_spring")
	_expect(resumed.exploration.restore({"map_id": "cangquan_path", "player_x": 0.68, "player_y": 0.60}), "E2E 重游到达山道药篓")
	resumed._render([])
	await _trigger_semantic_action(resumed, "interact")
	_expect(resumed.journey.discoveries == ["abandoned_basket"], "E2E 重游可只发现药篓见闻")
	_expect(resumed.exploration.restore({"map_id": "cangquan_path", "player_x": 0.10, "player_y": 0.68}), "E2E 重游带药篓返回山脚")
	resumed._render([])
	await _trigger_semantic_action(resumed, "interact")
	_expect(resumed.exploration.restore({"map_id": "zhaohe_ferry", "player_x": 0.75, "player_y": 0.66}), "E2E 重游到达蕙婶身旁")
	resumed._render([])
	await _trigger_semantic_action(resumed, "interact")
	resumed.skip_dialogue_to_response()
	await _settle()
	await _press_dialogue_choice(resumed, "补好提绳，留在山道。")
	_expect(resumed.journey.basket_response == "trail", "E2E 重游可选择补绳留山分支")
	_expect(resumed.get_node("%MapCanvas").basket_visual_contract()["repaired_on_trail"], "E2E 留山分支进入稳定地图表现状态")
	_expect(resumed.exploration.restore({"map_id": "zhaohe_ferry", "player_x": 0.88, "player_y": 0.18}), "E2E 重游再次到达山门")
	resumed._render([])
	await _trigger_semantic_action(resumed, "interact")
	_expect(resumed.exploration.restore({"map_id": "cangquan_path", "player_x": 0.86, "player_y": 0.18}), "E2E 重游后到达绕行入口")
	resumed._render([])
	await _trigger_semantic_action(resumed, "interact")
	_expect(resumed.journey.phase_id() == "spring", "E2E 沿溪绕行不进入战斗即可到泉室")
	_expect(resumed.journey.player_hp == 12 and resumed.journey.talismans == 1 and resumed.journey.round_number == 1, "E2E 绕行保留气血、符箓和战斗回合")
	await _press_action(resumed, "静心引息")
	_expect(resumed.get_node("%DescriptionLabel").text.contains("以信任同行"), "E2E 结算回应重游时的信任选择")
	_expect(resumed.get_node("%DescriptionLabel").text.contains("敌情 0/3"), "E2E 绕行结算不伪造未调查敌情")
	_expect(resumed.get_node("%DescriptionLabel").text.contains("月芽留根"), "E2E 结算回应重游时的采集选择")
	_expect(resumed.get_node("%DescriptionLabel").text.contains("涨时入簿"), "E2E 结算回应重游时的记时选择")
	await _press_action(resumed, "回顾此行")
	_expect(resumed.get_node("%DialogueLabel").text.contains("把月芽留了根"), "E2E 重游余波回显留根采集")
	_expect(resumed.get_node("%DialogueLabel").text.contains("沿途1处生活痕迹"), "E2E 重游余波只回显实际发现的一处见闻")
	_expect(resumed._resolved_dialogue_text("{setback_reflection}").contains("没有因求快而失手"), "E2E 无战绕行余波回显零挫败")
	_expect(resumed._resolved_dialogue_text("{companion_reflection}").contains("把判断交给同伴"), "E2E 余波回显重游时的信任回应")
	_expect(resumed._resolved_dialogue_text("{ferryman_reflection}").contains("守堤簿"), "E2E 余波回显重游时的记时结果")
	_expect(resumed._resolved_dialogue_text("{basket_reflection}").contains("仍在山道"), "E2E 余波回显重游时的药篓留山结果")
	_expect(resumed._resolved_dialogue_text("{intel_reflection}").contains("尚未辨明"), "E2E 绕行余波不伪造灵物情报")
	resumed.skip_dialogue_to_response()
	await _press_dialogue_choice(resumed, "明日再沿河走一趟。")
	_expect(resumed.get_node("%EventLabel").text.contains("修行已经开始"), "E2E 重游可选择另一项余波收束")
	resumed.return_to_title()
	resumed.get_node("%NewGameButton").pressed.emit()
	await _settle()
	resumed.get_node("%NewGameButton").pressed.emit()
	await _settle()
	_expect(not resumed.get_node("%TitleOverlay").visible, "E2E 第二次明确确认后重新开局")
	_expect(resumed.journey.phase_id() == "riverbank" and resumed.journey.ferryman_response == "unanswered" and resumed.journey.basket_response == "unanswered", "E2E 明确覆盖建立干净序章状态")
	_expect(SaveGameScript.read(TEST_SAVE_PATH)["data"]["journey"]["phase"] == "riverbank", "E2E 新序章状态已安全落盘")

	resumed.queue_free()
	await _settle()
	SaveGameScript.remove(TEST_SAVE_PATH)
	SettingsStoreScript.remove(TEST_SETTINGS_PATH)
	if failures.is_empty():
		print("RPG E2E passed: %d assertions, new game to replay." % assertions)
		quit(0)
	else:
		for failure in failures:
			push_error(failure)
		quit(1)


func _press_action(game: Node, label: String) -> void:
	for child in game.get_node("%Actions").get_children():
		if child is Button and child.text == label:
			child.pressed.emit()
			await _settle()
			return
	failures.append("E2E 找不到行动：%s" % label)


func _press_dialogue_choice(game: Node, label: String) -> void:
	for child in game.get_node("%DialogueChoices").get_children():
		if child is Button and child.text == label:
			child.pressed.emit()
			await _settle()
			return
	failures.append("E2E 找不到对话回应：%s" % label)


func _trigger_semantic_action(game: Node, action_name: StringName) -> void:
	var transition: Control = game.get_node("%SceneTransition")
	if transition.is_transitioning():
		transition.advance(1.0)
		await process_frame
	var pressed := InputEventAction.new()
	pressed.action = action_name
	pressed.pressed = true
	Input.parse_input_event(pressed)
	await process_frame
	var released := InputEventAction.new()
	released.action = action_name
	released.pressed = false
	Input.parse_input_event(released)
	await process_frame


func _settle() -> void:
	await process_frame
	await process_frame


func _expect(value: bool, label: String) -> void:
	assertions += 1
	if not value:
		failures.append("%s：期望 true" % label)
